import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'

// const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Header title="Fortunato Cooks"/>
      <p>Hello World!</p>
    </div>
  )
}

// import React from 'react';
// import ReactDOM from 'react-dom';
// import App from './App';

// if (typeof document !== 'undefined') {
//   ReactDOM.render(
//     <React.StrictMode>
//       <App />
//     </React.StrictMode>,
//     document.getElementById('root')
//   );
// }